name: Build .NET Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore .NET
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish (Linux)
      run: |
        find . -name "*.csproj" -exec dotnet publish {} --configuration Release --output "out/$(basename {} .csproj)" \;
      shell: bash
      if: matrix.os == 'ubuntu-latest'

    - name: Publish (Windows)
      run: |
        Get-ChildItem -Path . -Include *.csproj -Recurse | ForEach-Object {
          dotnet publish "$_" --configuration Release --output "out/$($_.BaseName)"
        }
      shell: pwsh
      if: matrix.os == 'windows-latest'

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.os }}
        path: out/